version: 0.2

phases:
  install:
    runtime-versions:
       dotnet: 2.2
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands: 
      - dotnet lambda package-ci --s3-bucket net-template -ot packaged.json
artifacts:
  files: 
    - packaged.json
    
    
    
    
