version: 0.2

phases:
  install:
    runtime-versions:
       dotnet: 2.2
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands: 
#       - dotnet lambda package-ci --s3-bucket net-template --output-template updated-packaged.json
#       dotnet lambda package-ci --s3-bucket utility-s3 --output-template updated-serverless.template
        - dotnet lambda package-ci --template serverless.template --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json
artifacts:
  files: 
#     - packaged.json
    -serverless.template.json
    
    
    
    
